name: (Windows x64) Build and publish

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Get short SHA
        run: echo "SHORT_SHA=$($env:GITHUB_SHA.SubString(0,7))" >> $env:GITHUB_ENV

      - name: Download OpenCV 4.5.1
        run: |
          mkdir C:\downloads
          $opencv_ver="4.5.1"
          curl -fL https://github.com/opencv/opencv/archive/${opencv_ver}.zip -o C:\downloads\opencv-${opencv_ver}.zip
          7z -r x C:\downloads\opencv-4.5.1.zip -oc:\downloads\
          ls

# cmake -G "MinGW Makefiles" -S C:\downloads\opencv-4.5.1\ -B C:\downloads\opencv-4.5.1\build_64\

      - name: Compile OpenCV
        run: |
          mkdir C:\downloads\opencv-4.5.1\build_64
          copy-item $env:GITHUB_WORKSPACE\ci\CMakeLists.txt C:\downloads\opencv-4.5.1\         

