name: (Windows x64) Build and publish

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Get short SHA
        run: echo "SHORT_SHA=$($env:GITHUB_SHA.SubString(0,7))" >> $env:GITHUB_ENV

      - name: Download OpenCV
        run: |
          mkdir C:\downloads
          $opencv_ver="4.5.1"
          curl -fL https://github.com/opencv/opencv/archive/${opencv_ver}.zip -o C:\downloads\opencv-${opencv_ver}.zip
          7z -r x C:\downloads\opencv-4.5.1.zip -oc:\downloads\
          echo OpenCV_DIR="C:\downloads\opencv-4.5.1" >> $env:GITHUB_ENV

      - name: Compile OpenCV
        run: |
          mkdir C:\downloads\opencv-4.5.1\build_64
          cmake -G "MinGW Makefiles" -S C:\downloads\opencv-4.5.1\ -B C:\downloads\opencv-4.5.1\build_64\ -D BUILD_JAVA=OFF -D WITH_QT=ON -D WITH_OPENGL=ON
          cd $env:OpenCV_DIR\build_64
          mingw32-make -j 8
          mingw32-make install
