# This is a basic workflow to help you get started with Actions

name: Build and publish artifacts

# Controls when the workflow will run
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download Precompiled OpenCV 4.5.1 (Win64)
        run: |
          mkdir C:\downloads
          pip install gdown
          gdown --id 1D0Op3M9LMxfDmjgsomGhki4hTAm4FKof --output C:\downloads\opencv-4.5.1.7z
          7z -r x C:\downloads\opencv-4.5.1.7z -oc:\downloads\
          Set-Content -Path OpenCV_DIR C:\downloads\opencv-4.5.1\
          
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw81'
          install-deps: 'true'
          dir: 'C:'
          tools: 'tools_ifw,4.1.1,qt.tools.ifw.41 tools_qtcreator,5.0.2-0,qt.tools.qtcreator,qt.tools.'

      - name: Add Qt to our env.var
        run: |
          ls C:\Qt
          ls C:\Qt\5.15.2\mingw81_64\bin
          Set-Content -Path Qt_Install C:\Qt
          Get-Content -Path Qt_Install

      - name: Build Trdrop for Win64
        run: |
          D:
          cd D:\a\trdrop\trdrop
          qmake.exe        -o Makefile trdrop\trdrop.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
          mingw32-make.exe -f Makefile.Release
          ls 
          ls release
