name: (Windows x64) Build and publish

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get short SHA
        run: echo "SHORT_SHA=$($env:GITHUB_SHA.SubString(0,7))" >> $env:GITHUB_ENV

      - name: Download OpenCV
        run: |
          mkdir C:\downloads
          $opencv_ver="4.5.1"
          curl -fL https://github.com/illusion0001/opencv-build/releases/download/${opencv_ver}/opencv-${opencv_ver}.7z -o C:\downloads\opencv-${opencv_ver}.7z
          7z -r x C:\downloads\opencv-${opencv_ver}.7z -oc:\downloads\
          ls C:\downloads\
          ls C:\downloads\opencv-${opencv_ver}
          ls C:\downloads\opencv-${opencv_ver}\build_64
          echo OpenCV_DIR="C:\downloads\opencv-${opencv_ver}" >> $env:GITHUB_ENV

      - name: Download Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.2
          arch: win64_mingw81
          dir: C:\
          tools: tools_ifw,4.1.1,qt.tools.ifw.41 tools_qtcreator,5.0.2-0,qt.tools.qtcreator,qt.tools.

      - name: Add Qt and MinGW to environment variable
        run: |
          echo Qt_Install="C:\Qt" >> $env:GITHUB_ENV
          echo MinGWBin="C:\msys64\mingw64\bin" >> $env:GITHUB_ENV

      - name: Build Trdrop
        run: |
          qmake -o Makefile trdrop\trdrop.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
          mingw32-make -f Makefile.Release

      - name: Prepare trdrop for artifact
        run: |
          cd $env:MinGWBin
          cp libgcc_s_seh-1.dll, libstdc++-6.dll, libwinpthread-1.dll, libgomp-1.dll $env:GITHUB_WORKSPACE\release
          cd $env:OpenCV_DIR\build_64\install\x64\mingw\bin
          cp libopencv_core451.dll, libopencv_imgcodecs451.dll, libopencv_imgproc451.dll, libopencv_videoio451.dll, opencv_videoio_ffmpeg451_64.dll $env:GITHUB_WORKSPACE\release
          windeployqt --qmldir $env:GITHUB_WORKSPACE $env:GITHUB_WORKSPACE\release

      - name: Cleanup for packaging
        run: |
          Remove-Item release\* -include *.c, *.cpp, *.h, *.o -exclude *.exe, *.dll
          cd release
          Remove-Item -Recurse -Force audio, bearer, iconengines, mediaservice, playlistformats, qmltooling, QtGraphicalEffects, styles, translations, D3Dcompiler_47.dll, opengl32sw.dll, libGLESv2.dll
          7z a -m0=LZMA2 -mx9 ..\trdrop-release-${env:SHORT_SHA}.7z

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: trdrop-release-${{ env.SHORT_SHA }}
          path: release/*
          if-no-files-found: error
          retention-days: 1

