name: (Windows x64) Build and publish

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Get short SHA
        run: echo "SHORT_SHA=$($env:GITHUB_SHA.SubString(0,7))" >> $env:GITHUB_ENV

      - name: Download OpenCV 4.5.1
        run: |
          mkdir C:\downloads
          Invoke-WebRequest -Uri https://github.com/opencv/opencv/archive/4.5.1.zip -OutFile C:\downloads\opencv-4.5.1.zip
          7z -r x C:\downloads\opencv-4.5.1.zip -oc:\downloads\

      - name: Compile OpenCV
        run: |
          mkdir C:\downloads\opencv-4.5.1\build_64
          cmake -G "MinGW Makefiles" -S C:\downloads\opencv-4.5.1\ -B C:\downloads\opencv-4.5.1\build_64\
          

