name: (Windows x64) Build and publish

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Get short SHA and set Qt + OpenCV version
        run: |
          ls C:\
          New-Item -ItemType SymbolicLink -Path "C:\msys64" -Target "C:\msys64"
