name: (Windows x64) Build and publish

on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Workaround tar path failure
      # Grant local admins full access to the system file (very sus..)
      # https://kimconnect.com/powershell-how-to-replace-a-system-file-for-experimentation-purposes/
        run: |
          Set-Acl C:\Windows\System32\tar.exe New-Object System.Security.AccessControl.FileSystemAccessRule("Administrators","Full","Allow")
          Rename-item C:\Windows\System32\tar.exe C:\Windows\System32\tar.exe.bak
          copy-item "C:\Program Files\Git\usr\bin\tar.exe" C:\Windows\System32\tar.exe
