name: test

on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Workaround tar path failure
      # Grant local admins full access to the system file (very sus..)
      # https://kimconnect.com/powershell-how-to-replace-a-system-file-for-experimentation-purposes/
        run: |
          $notepadExe='C:\Windows\System32\tar.exe'
          $acl = Get-ACL $notepadExe
          $acl.AddAccessRule(New-Object System.Security.AccessControl.FileSystemAccessRule("Administrators","Full","Allow"))
          Set-Acl $notepadExe $acl
          Rename-item C:\Windows\System32\tar.exe C:\Windows\System32\tar.exe.bak
          copy-item "C:\Program Files\Git\usr\bin\tar.exe" C:\Windows\System32\tar.exe
